# Generated by Django 2.1 on 2018-08-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis', '0003_auto_20180830_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fk_author',
            field=models.ManyToManyField(to='cannabis.Author'),
        ),
    ]
