# Generated by Django 2.1 on 2018-08-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis', '0004_article_fk_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fk_author',
            field=models.ManyToManyField(limit_choices_to={'name': 'H Neels'}, to='cannabis.Author'),
        ),
        migrations.AlterField(
            model_name='articleresearch',
            name='number_of_pations',
            field=models.IntegerField(),
        ),
    ]
