# Generated by Django 2.1 on 2018-09-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis', '0007_auto_20180910_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientgroup',
            name='combination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientgroup',
            name='fk_gender_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis.Gender'),
        ),
        migrations.AlterField(
            model_name='patientgroup',
            name='number_of_patient',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientgroup',
            name='second_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cannabis.Disease'),
        ),
        migrations.AlterField(
            model_name='patientgroup',
            name='years_max',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patientgroup',
            name='years_min',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
