# Generated by Django 2.1 on 2018-09-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis', '0010_auto_20180911_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fk_article_research',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis.ArticleResearch'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fk_author',
            field=models.ManyToManyField(blank=True, null=True, to='cannabis.Author'),
        ),
    ]
