# Generated by Django 2.1 on 2018-09-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis', '0011_auto_20180912_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pubmed',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='articleresearch',
            name='number_of_pations',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
