# Generated by Django 2.1 on 2018-09-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis', '0015_auto_20180913_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleresearch',
            name='number_of_pations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
