# Generated by Django 2.1 on 2018-09-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis', '0016_auto_20180913_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleArticleResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cannabis.Article')),
                ('fk_article_research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cannabis.ArticleResearch')),
            ],
        ),
    ]
