# Generated by Django 2.1 on 2018-09-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cannabis', '0017_articlearticleresearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlearticleresearch',
            name='fk_article',
        ),
        migrations.RemoveField(
            model_name='articlearticleresearch',
            name='fk_article_research',
        ),
        migrations.DeleteModel(
            name='ArticleArticleResearch',
        ),
    ]
